# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\x12\x04slam\"\'\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"Y\n\x05\x63vMat\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x10\n\x08\x65lt_type\x18\x03 \x01(\x05\x12\x10\n\x08\x65lt_size\x18\x04 \x01(\x05\x12\x10\n\x08mat_data\x18\x05 \x01(\x0c\"\xc1\x01\n\x05\x46rame\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rpath_to_image\x18\x02 \x01(\x0c\x12\x19\n\x04\x64\x65sc\x18\x03 \x01(\x0b\x32\x0b.slam.cvMat\x12.\n\nbow_vector\x18\x04 \x03(\x0b\x32\x1a.slam.Frame.BowVectorEntry\x12\x18\n\x04pose\x18\x05 \x01(\x0b\x32\n.slam.Pose\x1a\x30\n\x0e\x42owVectorEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"$\n\x06\x46rames\x12\x1a\n\x05\x65lems\x18\x01 \x03(\x0b\x32\x0b.slam.Frameb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRAME_BOWVECTORENTRY._options = None
  _FRAME_BOWVECTORENTRY._serialized_options = b'8\001'
  _POSE._serialized_start=21
  _POSE._serialized_end=60
  _CVMAT._serialized_start=62
  _CVMAT._serialized_end=151
  _FRAME._serialized_start=154
  _FRAME._serialized_end=347
  _FRAME_BOWVECTORENTRY._serialized_start=299
  _FRAME_BOWVECTORENTRY._serialized_end=347
  _FRAMES._serialized_start=349
  _FRAMES._serialized_end=385
# @@protoc_insertion_point(module_scope)
