// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_frame_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_frame_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_frame_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_frame_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_frame_2eproto;
namespace slam {
class Frame;
struct FrameDefaultTypeInternal;
extern FrameDefaultTypeInternal _Frame_default_instance_;
class Frame_BowVectorEntry_DoNotUse;
struct Frame_BowVectorEntry_DoNotUseDefaultTypeInternal;
extern Frame_BowVectorEntry_DoNotUseDefaultTypeInternal _Frame_BowVectorEntry_DoNotUse_default_instance_;
class Frames;
struct FramesDefaultTypeInternal;
extern FramesDefaultTypeInternal _Frames_default_instance_;
class Pose;
struct PoseDefaultTypeInternal;
extern PoseDefaultTypeInternal _Pose_default_instance_;
class cvMat;
struct cvMatDefaultTypeInternal;
extern cvMatDefaultTypeInternal _cvMat_default_instance_;
}  // namespace slam
PROTOBUF_NAMESPACE_OPEN
template<> ::slam::Frame* Arena::CreateMaybeMessage<::slam::Frame>(Arena*);
template<> ::slam::Frame_BowVectorEntry_DoNotUse* Arena::CreateMaybeMessage<::slam::Frame_BowVectorEntry_DoNotUse>(Arena*);
template<> ::slam::Frames* Arena::CreateMaybeMessage<::slam::Frames>(Arena*);
template<> ::slam::Pose* Arena::CreateMaybeMessage<::slam::Pose>(Arena*);
template<> ::slam::cvMat* Arena::CreateMaybeMessage<::slam::cvMat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace slam {

// ===================================================================

class Pose final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:slam.Pose) */ {
 public:
  inline Pose() : Pose(nullptr) {}
  ~Pose() override;
  explicit PROTOBUF_CONSTEXPR Pose(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Pose(const Pose& from);
  Pose(Pose&& from) noexcept
    : Pose() {
    *this = ::std::move(from);
  }

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }
  inline Pose& operator=(Pose&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Pose& default_instance() {
    return *internal_default_instance();
  }
  static inline const Pose* internal_default_instance() {
    return reinterpret_cast<const Pose*>(
               &_Pose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Pose& a, Pose& b) {
    a.Swap(&b);
  }
  inline void Swap(Pose* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Pose* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Pose* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Pose>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Pose& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Pose& from) {
    Pose::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Pose* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "slam.Pose";
  }
  protected:
  explicit Pose(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:slam.Pose)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_frame_2eproto;
};
// -------------------------------------------------------------------

class cvMat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:slam.cvMat) */ {
 public:
  inline cvMat() : cvMat(nullptr) {}
  ~cvMat() override;
  explicit PROTOBUF_CONSTEXPR cvMat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  cvMat(const cvMat& from);
  cvMat(cvMat&& from) noexcept
    : cvMat() {
    *this = ::std::move(from);
  }

  inline cvMat& operator=(const cvMat& from) {
    CopyFrom(from);
    return *this;
  }
  inline cvMat& operator=(cvMat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cvMat& default_instance() {
    return *internal_default_instance();
  }
  static inline const cvMat* internal_default_instance() {
    return reinterpret_cast<const cvMat*>(
               &_cvMat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(cvMat& a, cvMat& b) {
    a.Swap(&b);
  }
  inline void Swap(cvMat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cvMat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cvMat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<cvMat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const cvMat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const cvMat& from) {
    cvMat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(cvMat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "slam.cvMat";
  }
  protected:
  explicit cvMat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMatDataFieldNumber = 5,
    kRowsFieldNumber = 1,
    kColsFieldNumber = 2,
    kEltTypeFieldNumber = 3,
    kEltSizeFieldNumber = 4,
  };
  // bytes mat_data = 5;
  void clear_mat_data();
  const std::string& mat_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mat_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mat_data();
  PROTOBUF_NODISCARD std::string* release_mat_data();
  void set_allocated_mat_data(std::string* mat_data);
  private:
  const std::string& _internal_mat_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mat_data(const std::string& value);
  std::string* _internal_mutable_mat_data();
  public:

  // int32 rows = 1;
  void clear_rows();
  int32_t rows() const;
  void set_rows(int32_t value);
  private:
  int32_t _internal_rows() const;
  void _internal_set_rows(int32_t value);
  public:

  // int32 cols = 2;
  void clear_cols();
  int32_t cols() const;
  void set_cols(int32_t value);
  private:
  int32_t _internal_cols() const;
  void _internal_set_cols(int32_t value);
  public:

  // int32 elt_type = 3;
  void clear_elt_type();
  int32_t elt_type() const;
  void set_elt_type(int32_t value);
  private:
  int32_t _internal_elt_type() const;
  void _internal_set_elt_type(int32_t value);
  public:

  // int32 elt_size = 4;
  void clear_elt_size();
  int32_t elt_size() const;
  void set_elt_size(int32_t value);
  private:
  int32_t _internal_elt_size() const;
  void _internal_set_elt_size(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:slam.cvMat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mat_data_;
    int32_t rows_;
    int32_t cols_;
    int32_t elt_type_;
    int32_t elt_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_frame_2eproto;
};
// -------------------------------------------------------------------

class Frame_BowVectorEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Frame_BowVectorEntry_DoNotUse, 
    uint32_t, double,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Frame_BowVectorEntry_DoNotUse, 
    uint32_t, double,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> SuperType;
  Frame_BowVectorEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Frame_BowVectorEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Frame_BowVectorEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Frame_BowVectorEntry_DoNotUse& other);
  static const Frame_BowVectorEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Frame_BowVectorEntry_DoNotUse*>(&_Frame_BowVectorEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_frame_2eproto;
};

// -------------------------------------------------------------------

class Frame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:slam.Frame) */ {
 public:
  inline Frame() : Frame(nullptr) {}
  ~Frame() override;
  explicit PROTOBUF_CONSTEXPR Frame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Frame(const Frame& from);
  Frame(Frame&& from) noexcept
    : Frame() {
    *this = ::std::move(from);
  }

  inline Frame& operator=(const Frame& from) {
    CopyFrom(from);
    return *this;
  }
  inline Frame& operator=(Frame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Frame& default_instance() {
    return *internal_default_instance();
  }
  static inline const Frame* internal_default_instance() {
    return reinterpret_cast<const Frame*>(
               &_Frame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Frame& a, Frame& b) {
    a.Swap(&b);
  }
  inline void Swap(Frame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Frame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Frame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Frame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Frame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Frame& from) {
    Frame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Frame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "slam.Frame";
  }
  protected:
  explicit Frame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kBowVectorFieldNumber = 4,
    kPathToImageFieldNumber = 2,
    kDescFieldNumber = 3,
    kPoseFieldNumber = 5,
    kIdFieldNumber = 1,
  };
  // map<uint32, double> bow_vector = 4;
  int bow_vector_size() const;
  private:
  int _internal_bow_vector_size() const;
  public:
  void clear_bow_vector();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >&
      _internal_bow_vector() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >*
      _internal_mutable_bow_vector();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >&
      bow_vector() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >*
      mutable_bow_vector();

  // bytes path_to_image = 2;
  void clear_path_to_image();
  const std::string& path_to_image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_to_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_to_image();
  PROTOBUF_NODISCARD std::string* release_path_to_image();
  void set_allocated_path_to_image(std::string* path_to_image);
  private:
  const std::string& _internal_path_to_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_to_image(const std::string& value);
  std::string* _internal_mutable_path_to_image();
  public:

  // .slam.cvMat desc = 3;
  bool has_desc() const;
  private:
  bool _internal_has_desc() const;
  public:
  void clear_desc();
  const ::slam::cvMat& desc() const;
  PROTOBUF_NODISCARD ::slam::cvMat* release_desc();
  ::slam::cvMat* mutable_desc();
  void set_allocated_desc(::slam::cvMat* desc);
  private:
  const ::slam::cvMat& _internal_desc() const;
  ::slam::cvMat* _internal_mutable_desc();
  public:
  void unsafe_arena_set_allocated_desc(
      ::slam::cvMat* desc);
  ::slam::cvMat* unsafe_arena_release_desc();

  // .slam.Pose pose = 5;
  bool has_pose() const;
  private:
  bool _internal_has_pose() const;
  public:
  void clear_pose();
  const ::slam::Pose& pose() const;
  PROTOBUF_NODISCARD ::slam::Pose* release_pose();
  ::slam::Pose* mutable_pose();
  void set_allocated_pose(::slam::Pose* pose);
  private:
  const ::slam::Pose& _internal_pose() const;
  ::slam::Pose* _internal_mutable_pose();
  public:
  void unsafe_arena_set_allocated_pose(
      ::slam::Pose* pose);
  ::slam::Pose* unsafe_arena_release_pose();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:slam.Frame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Frame_BowVectorEntry_DoNotUse,
        uint32_t, double,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> bow_vector_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_to_image_;
    ::slam::cvMat* desc_;
    ::slam::Pose* pose_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_frame_2eproto;
};
// -------------------------------------------------------------------

class Frames final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:slam.Frames) */ {
 public:
  inline Frames() : Frames(nullptr) {}
  ~Frames() override;
  explicit PROTOBUF_CONSTEXPR Frames(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Frames(const Frames& from);
  Frames(Frames&& from) noexcept
    : Frames() {
    *this = ::std::move(from);
  }

  inline Frames& operator=(const Frames& from) {
    CopyFrom(from);
    return *this;
  }
  inline Frames& operator=(Frames&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Frames& default_instance() {
    return *internal_default_instance();
  }
  static inline const Frames* internal_default_instance() {
    return reinterpret_cast<const Frames*>(
               &_Frames_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Frames& a, Frames& b) {
    a.Swap(&b);
  }
  inline void Swap(Frames* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Frames* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Frames* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Frames>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Frames& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Frames& from) {
    Frames::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Frames* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "slam.Frames";
  }
  protected:
  explicit Frames(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kElemsFieldNumber = 1,
  };
  // repeated .slam.Frame elems = 1;
  int elems_size() const;
  private:
  int _internal_elems_size() const;
  public:
  void clear_elems();
  ::slam::Frame* mutable_elems(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::slam::Frame >*
      mutable_elems();
  private:
  const ::slam::Frame& _internal_elems(int index) const;
  ::slam::Frame* _internal_add_elems();
  public:
  const ::slam::Frame& elems(int index) const;
  ::slam::Frame* add_elems();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::slam::Frame >&
      elems() const;

  // @@protoc_insertion_point(class_scope:slam.Frames)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::slam::Frame > elems_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_frame_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Pose

// double x = 1;
inline void Pose::clear_x() {
  _impl_.x_ = 0;
}
inline double Pose::_internal_x() const {
  return _impl_.x_;
}
inline double Pose::x() const {
  // @@protoc_insertion_point(field_get:slam.Pose.x)
  return _internal_x();
}
inline void Pose::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Pose::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:slam.Pose.x)
}

// double y = 2;
inline void Pose::clear_y() {
  _impl_.y_ = 0;
}
inline double Pose::_internal_y() const {
  return _impl_.y_;
}
inline double Pose::y() const {
  // @@protoc_insertion_point(field_get:slam.Pose.y)
  return _internal_y();
}
inline void Pose::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Pose::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:slam.Pose.y)
}

// double z = 3;
inline void Pose::clear_z() {
  _impl_.z_ = 0;
}
inline double Pose::_internal_z() const {
  return _impl_.z_;
}
inline double Pose::z() const {
  // @@protoc_insertion_point(field_get:slam.Pose.z)
  return _internal_z();
}
inline void Pose::_internal_set_z(double value) {
  
  _impl_.z_ = value;
}
inline void Pose::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:slam.Pose.z)
}

// -------------------------------------------------------------------

// cvMat

// int32 rows = 1;
inline void cvMat::clear_rows() {
  _impl_.rows_ = 0;
}
inline int32_t cvMat::_internal_rows() const {
  return _impl_.rows_;
}
inline int32_t cvMat::rows() const {
  // @@protoc_insertion_point(field_get:slam.cvMat.rows)
  return _internal_rows();
}
inline void cvMat::_internal_set_rows(int32_t value) {
  
  _impl_.rows_ = value;
}
inline void cvMat::set_rows(int32_t value) {
  _internal_set_rows(value);
  // @@protoc_insertion_point(field_set:slam.cvMat.rows)
}

// int32 cols = 2;
inline void cvMat::clear_cols() {
  _impl_.cols_ = 0;
}
inline int32_t cvMat::_internal_cols() const {
  return _impl_.cols_;
}
inline int32_t cvMat::cols() const {
  // @@protoc_insertion_point(field_get:slam.cvMat.cols)
  return _internal_cols();
}
inline void cvMat::_internal_set_cols(int32_t value) {
  
  _impl_.cols_ = value;
}
inline void cvMat::set_cols(int32_t value) {
  _internal_set_cols(value);
  // @@protoc_insertion_point(field_set:slam.cvMat.cols)
}

// int32 elt_type = 3;
inline void cvMat::clear_elt_type() {
  _impl_.elt_type_ = 0;
}
inline int32_t cvMat::_internal_elt_type() const {
  return _impl_.elt_type_;
}
inline int32_t cvMat::elt_type() const {
  // @@protoc_insertion_point(field_get:slam.cvMat.elt_type)
  return _internal_elt_type();
}
inline void cvMat::_internal_set_elt_type(int32_t value) {
  
  _impl_.elt_type_ = value;
}
inline void cvMat::set_elt_type(int32_t value) {
  _internal_set_elt_type(value);
  // @@protoc_insertion_point(field_set:slam.cvMat.elt_type)
}

// int32 elt_size = 4;
inline void cvMat::clear_elt_size() {
  _impl_.elt_size_ = 0;
}
inline int32_t cvMat::_internal_elt_size() const {
  return _impl_.elt_size_;
}
inline int32_t cvMat::elt_size() const {
  // @@protoc_insertion_point(field_get:slam.cvMat.elt_size)
  return _internal_elt_size();
}
inline void cvMat::_internal_set_elt_size(int32_t value) {
  
  _impl_.elt_size_ = value;
}
inline void cvMat::set_elt_size(int32_t value) {
  _internal_set_elt_size(value);
  // @@protoc_insertion_point(field_set:slam.cvMat.elt_size)
}

// bytes mat_data = 5;
inline void cvMat::clear_mat_data() {
  _impl_.mat_data_.ClearToEmpty();
}
inline const std::string& cvMat::mat_data() const {
  // @@protoc_insertion_point(field_get:slam.cvMat.mat_data)
  return _internal_mat_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void cvMat::set_mat_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mat_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:slam.cvMat.mat_data)
}
inline std::string* cvMat::mutable_mat_data() {
  std::string* _s = _internal_mutable_mat_data();
  // @@protoc_insertion_point(field_mutable:slam.cvMat.mat_data)
  return _s;
}
inline const std::string& cvMat::_internal_mat_data() const {
  return _impl_.mat_data_.Get();
}
inline void cvMat::_internal_set_mat_data(const std::string& value) {
  
  _impl_.mat_data_.Set(value, GetArenaForAllocation());
}
inline std::string* cvMat::_internal_mutable_mat_data() {
  
  return _impl_.mat_data_.Mutable(GetArenaForAllocation());
}
inline std::string* cvMat::release_mat_data() {
  // @@protoc_insertion_point(field_release:slam.cvMat.mat_data)
  return _impl_.mat_data_.Release();
}
inline void cvMat::set_allocated_mat_data(std::string* mat_data) {
  if (mat_data != nullptr) {
    
  } else {
    
  }
  _impl_.mat_data_.SetAllocated(mat_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mat_data_.IsDefault()) {
    _impl_.mat_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:slam.cvMat.mat_data)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Frame

// int32 id = 1;
inline void Frame::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Frame::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Frame::id() const {
  // @@protoc_insertion_point(field_get:slam.Frame.id)
  return _internal_id();
}
inline void Frame::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Frame::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:slam.Frame.id)
}

// bytes path_to_image = 2;
inline void Frame::clear_path_to_image() {
  _impl_.path_to_image_.ClearToEmpty();
}
inline const std::string& Frame::path_to_image() const {
  // @@protoc_insertion_point(field_get:slam.Frame.path_to_image)
  return _internal_path_to_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Frame::set_path_to_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.path_to_image_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:slam.Frame.path_to_image)
}
inline std::string* Frame::mutable_path_to_image() {
  std::string* _s = _internal_mutable_path_to_image();
  // @@protoc_insertion_point(field_mutable:slam.Frame.path_to_image)
  return _s;
}
inline const std::string& Frame::_internal_path_to_image() const {
  return _impl_.path_to_image_.Get();
}
inline void Frame::_internal_set_path_to_image(const std::string& value) {
  
  _impl_.path_to_image_.Set(value, GetArenaForAllocation());
}
inline std::string* Frame::_internal_mutable_path_to_image() {
  
  return _impl_.path_to_image_.Mutable(GetArenaForAllocation());
}
inline std::string* Frame::release_path_to_image() {
  // @@protoc_insertion_point(field_release:slam.Frame.path_to_image)
  return _impl_.path_to_image_.Release();
}
inline void Frame::set_allocated_path_to_image(std::string* path_to_image) {
  if (path_to_image != nullptr) {
    
  } else {
    
  }
  _impl_.path_to_image_.SetAllocated(path_to_image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.path_to_image_.IsDefault()) {
    _impl_.path_to_image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:slam.Frame.path_to_image)
}

// .slam.cvMat desc = 3;
inline bool Frame::_internal_has_desc() const {
  return this != internal_default_instance() && _impl_.desc_ != nullptr;
}
inline bool Frame::has_desc() const {
  return _internal_has_desc();
}
inline void Frame::clear_desc() {
  if (GetArenaForAllocation() == nullptr && _impl_.desc_ != nullptr) {
    delete _impl_.desc_;
  }
  _impl_.desc_ = nullptr;
}
inline const ::slam::cvMat& Frame::_internal_desc() const {
  const ::slam::cvMat* p = _impl_.desc_;
  return p != nullptr ? *p : reinterpret_cast<const ::slam::cvMat&>(
      ::slam::_cvMat_default_instance_);
}
inline const ::slam::cvMat& Frame::desc() const {
  // @@protoc_insertion_point(field_get:slam.Frame.desc)
  return _internal_desc();
}
inline void Frame::unsafe_arena_set_allocated_desc(
    ::slam::cvMat* desc) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.desc_);
  }
  _impl_.desc_ = desc;
  if (desc) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:slam.Frame.desc)
}
inline ::slam::cvMat* Frame::release_desc() {
  
  ::slam::cvMat* temp = _impl_.desc_;
  _impl_.desc_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::slam::cvMat* Frame::unsafe_arena_release_desc() {
  // @@protoc_insertion_point(field_release:slam.Frame.desc)
  
  ::slam::cvMat* temp = _impl_.desc_;
  _impl_.desc_ = nullptr;
  return temp;
}
inline ::slam::cvMat* Frame::_internal_mutable_desc() {
  
  if (_impl_.desc_ == nullptr) {
    auto* p = CreateMaybeMessage<::slam::cvMat>(GetArenaForAllocation());
    _impl_.desc_ = p;
  }
  return _impl_.desc_;
}
inline ::slam::cvMat* Frame::mutable_desc() {
  ::slam::cvMat* _msg = _internal_mutable_desc();
  // @@protoc_insertion_point(field_mutable:slam.Frame.desc)
  return _msg;
}
inline void Frame::set_allocated_desc(::slam::cvMat* desc) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.desc_;
  }
  if (desc) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(desc);
    if (message_arena != submessage_arena) {
      desc = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, desc, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.desc_ = desc;
  // @@protoc_insertion_point(field_set_allocated:slam.Frame.desc)
}

// map<uint32, double> bow_vector = 4;
inline int Frame::_internal_bow_vector_size() const {
  return _impl_.bow_vector_.size();
}
inline int Frame::bow_vector_size() const {
  return _internal_bow_vector_size();
}
inline void Frame::clear_bow_vector() {
  _impl_.bow_vector_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >&
Frame::_internal_bow_vector() const {
  return _impl_.bow_vector_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >&
Frame::bow_vector() const {
  // @@protoc_insertion_point(field_map:slam.Frame.bow_vector)
  return _internal_bow_vector();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >*
Frame::_internal_mutable_bow_vector() {
  return _impl_.bow_vector_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, double >*
Frame::mutable_bow_vector() {
  // @@protoc_insertion_point(field_mutable_map:slam.Frame.bow_vector)
  return _internal_mutable_bow_vector();
}

// .slam.Pose pose = 5;
inline bool Frame::_internal_has_pose() const {
  return this != internal_default_instance() && _impl_.pose_ != nullptr;
}
inline bool Frame::has_pose() const {
  return _internal_has_pose();
}
inline void Frame::clear_pose() {
  if (GetArenaForAllocation() == nullptr && _impl_.pose_ != nullptr) {
    delete _impl_.pose_;
  }
  _impl_.pose_ = nullptr;
}
inline const ::slam::Pose& Frame::_internal_pose() const {
  const ::slam::Pose* p = _impl_.pose_;
  return p != nullptr ? *p : reinterpret_cast<const ::slam::Pose&>(
      ::slam::_Pose_default_instance_);
}
inline const ::slam::Pose& Frame::pose() const {
  // @@protoc_insertion_point(field_get:slam.Frame.pose)
  return _internal_pose();
}
inline void Frame::unsafe_arena_set_allocated_pose(
    ::slam::Pose* pose) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pose_);
  }
  _impl_.pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:slam.Frame.pose)
}
inline ::slam::Pose* Frame::release_pose() {
  
  ::slam::Pose* temp = _impl_.pose_;
  _impl_.pose_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::slam::Pose* Frame::unsafe_arena_release_pose() {
  // @@protoc_insertion_point(field_release:slam.Frame.pose)
  
  ::slam::Pose* temp = _impl_.pose_;
  _impl_.pose_ = nullptr;
  return temp;
}
inline ::slam::Pose* Frame::_internal_mutable_pose() {
  
  if (_impl_.pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::slam::Pose>(GetArenaForAllocation());
    _impl_.pose_ = p;
  }
  return _impl_.pose_;
}
inline ::slam::Pose* Frame::mutable_pose() {
  ::slam::Pose* _msg = _internal_mutable_pose();
  // @@protoc_insertion_point(field_mutable:slam.Frame.pose)
  return _msg;
}
inline void Frame::set_allocated_pose(::slam::Pose* pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pose_;
  }
  if (pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pose);
    if (message_arena != submessage_arena) {
      pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:slam.Frame.pose)
}

// -------------------------------------------------------------------

// Frames

// repeated .slam.Frame elems = 1;
inline int Frames::_internal_elems_size() const {
  return _impl_.elems_.size();
}
inline int Frames::elems_size() const {
  return _internal_elems_size();
}
inline void Frames::clear_elems() {
  _impl_.elems_.Clear();
}
inline ::slam::Frame* Frames::mutable_elems(int index) {
  // @@protoc_insertion_point(field_mutable:slam.Frames.elems)
  return _impl_.elems_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::slam::Frame >*
Frames::mutable_elems() {
  // @@protoc_insertion_point(field_mutable_list:slam.Frames.elems)
  return &_impl_.elems_;
}
inline const ::slam::Frame& Frames::_internal_elems(int index) const {
  return _impl_.elems_.Get(index);
}
inline const ::slam::Frame& Frames::elems(int index) const {
  // @@protoc_insertion_point(field_get:slam.Frames.elems)
  return _internal_elems(index);
}
inline ::slam::Frame* Frames::_internal_add_elems() {
  return _impl_.elems_.Add();
}
inline ::slam::Frame* Frames::add_elems() {
  ::slam::Frame* _add = _internal_add_elems();
  // @@protoc_insertion_point(field_add:slam.Frames.elems)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::slam::Frame >&
Frames::elems() const {
  // @@protoc_insertion_point(field_list:slam.Frames.elems)
  return _impl_.elems_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace slam

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_frame_2eproto
