FROM nvcr.io/nvidia/pytorch:22.08-py3

RUN pip install h5py==2.10.0 \
    && pip install faiss-gpu \
    && pip install tensorboardX \
    && pip install kapture \
    && pip install kapture-localization

